#!/bin/bash

#check if .bashrc exists 

if [ -f "$HOME/.bashrc" ]; then

	#append environment variables

	echo "export HELLO=$HOSTNAME" >> "$HOME/.bashrc"
	echo "LOCAL=$(whoami)" >> "$HOME/.bashrc"

	gnome-terminal
else

	echo ".bashrc not found"

fi
